PROJECT_NAME := deps
PROJ_VERSION := 1.0

# Set this variable to the top of the LLVM source tree.
LLVM_SRC_ROOT = /Users/dbz5017/Research/Projects/llvm-dsa

# Set this variable to the top level directory where LLVM was built
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
LLVM_OBJ_ROOT = /Users/dbz5017/Research/Projects/llvm-dsa

# Set the source root and source directory pathnames
####PROJ_SRC_DIR := $(subst //,/,/Users/dbz5017/Research/Projects/llvm-dsa/projects/llvm-deps/$(patsubst $(PROJ_OBJ_ROOT)%,%,$(PROJ_OBJ_DIR)))

PROJ_SRC_ROOT := $(subst //,/,/Users/dbz5017/Research/Projects/llvm-dsa/projects/llvm-deps)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(subst //,/,/Users/dbz5017/Research/Projects/llvm-dsa/projects/llvm-deps)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := /usr/local

# Set the location of the pool allocation project
POOLALLOC_SRCDIR := /Users/dbz5017/Research/Projects/llvm-dsa/projects/poolalloc
POOLALLOC_OBJDIR := /Users/dbz5017/Research/Projects/llvm-dsa/projects/poolalloc

# Set the location for dsa include
CFLAGS += -I~/llvm-dsa/projects/poolalloc/include
CXXFLAGS += -I~/llvm-dsa/projects/poolalloc/include
CPPFLAGS += -I~/llvm-dsa/projects/poolalloc/include

# Set the location of the LLVM Test Suite
TEST_SRCDIR := /Users/dbz5017/Research/Projects/llvm-dsa/projects/llvm-deps
TEST_OBJDIR := /Users/dbz5017/Research/Projects/llvm-dsa/projects/llvm-deps

# All of the code should additionally look inside the pool allocation source
# code for include files
SC_FLAGS = -DSAFECODE -I$(POOLALLOC_SRCDIR)/include -I$(POOLALLOC_OBJDIR)/include -Wall -fexceptions
CFLAGS   += $(SC_FLAGS)
CPPFLAGS += $(SC_FLAGS)
CXXFLAGS += $(SC_FLAGS) -Wno-deprecated -Wno-overloaded-virtual

# Include LLVM's Master Makefile.
include $(LLVM_SRC_ROOT)/Makefile.common
